name: talktime
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_webrtc: 1.2.1 # WebRTC for video/audio/screen share
  provider: ^6.1.2 # Or use Riverpod (we'll use Provider for simplicity now)
  shared_preferences: ^2.2.2 # For storing tokens/user data
  http: ^1.1.0 # For API calls
  equatable: ^2.0.5 # Clean model classes
  uuid: ^4.3.3 # Generate message/call IDs
  permission_handler: ^12.0.1 # Handle mic/camera permissions
  path_provider: ^2.1.1 # Needed for screen sharing on mobile
  get_it: ^9.2.0 # Service locator (optional but helpful)
  logger: ^2.0.2 # Logging
  web_socket_channel: ^3.0.3 # signaling
  signalr_netcore: ^1.4.4 # SignalR client for real-time communication
  flutter_dotenv: ^6.0.0
  flutter_nnnoiseless: ^1.0.1
  audio_service: ^0.18.18
  flutter_background_service: ^5.1.0
  sqflite: ^2.4.2
  path: ^1.9.1
  sqflite_common_ffi:
  sqflite_common_ffi_web:
  intl: ^0.20.2
  emoji_picker_flutter: ^4.4.0
  characters: ^1.4.0
  visibility_detector: ^0.4.0+2
  image_picker: ^1.2.1
  giphy_get: ^3.5.6
  cached_network_image: ^3.3.1
  http_parser: ^4.0.2
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  device_info_plus: ^12.3.0
  sqlite3_flutter_libs:
  flutter_callkit_incoming: ^3.0.0
  pip: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - .env
